import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { api } from '../api';
import { useWorkspace } from '../app/WorkspaceContext';
import { EmptyState, ErrorState, LoadingState, PageHeader } from '../components/PageState';
import { StatusPill } from '../components/StatusPill';

export function EvidencePage() {
  const { workspaceId } = useWorkspace(); const [draft, setDraft] = useState(''); const [search, setSearch] = useState(''); const [selected, setSelected] = useState('');
  const artifacts = useQuery({ queryKey: ['evidence', workspaceId], queryFn: () => api.evidence(workspaceId), enabled: !!workspaceId && !search });
  const results = useQuery({ queryKey: ['evidence-search', workspaceId, search], queryFn: () => api.searchEvidence(workspaceId, search), enabled: !!workspaceId && !!search });
  const detail = useQuery({ queryKey: ['evidence-detail', workspaceId, selected], queryFn: () => api.evidenceDetail(workspaceId, selected), enabled: !!selected });
  const data = search ? (results.data || []).map(item => ({ id: item.artifactId, title: item.title, artifactType: item.artifactType, sourceProvider: item.retrievalStage, lifecycleState: 'CURRENT', canonicalUrl: item.canonicalUrl, snippet: item.content, version: item.sourceVersion })) : (artifacts.data || []).map(item => ({ ...item, snippet: '', version: '' }));
  return <><PageHeader eyebrow="TEMPORAL EVIDENCE CATALOG" title="Every claim traces to a source version" description="Search requirements, ADRs, runbooks, incidents, contracts, builds, deployments, and documents with bounded graph expansion." />
    <form className="search-bar" role="search" onSubmit={event => { event.preventDefault(); setSearch(draft.trim()) }}><label className="sr-only" htmlFor="evidence-search">Search evidence</label><input id="evidence-search" value={draft} onChange={event => setDraft(event.target.value)} placeholder="Try ‘customer API compatibility’" /><button className="primary">Search evidence</button>{search && <button type="button" className="text-button" onClick={() => { setSearch(''); setDraft('') }}>Clear</button>}</form>
    {(artifacts.isLoading || results.isLoading) ? <LoadingState /> : (artifacts.error || results.error) ? <ErrorState error={artifacts.error || results.error} /> : !data.length ? <EmptyState title="No evidence found" body="Sync a connection, load the demo, or import existing document sources." /> : <section className="explorer-grid"><div className="evidence-list">{data.map(item => <button className={selected === item.id ? 'evidence-card selected' : 'evidence-card'} onClick={() => setSelected(item.id)} key={item.id}><div><span className="source-badge">{item.sourceProvider}</span><span>{item.artifactType.replaceAll('_', ' ')}</span></div><h2>{item.title}</h2>{item.snippet && <p>{item.snippet.slice(0, 220)}{item.snippet.length > 220 ? '…' : ''}</p>}<footer><StatusPill value={item.lifecycleState} />{item.version && <code>v{item.version}</code>}</footer></button>)}</div><aside className="evidence-preview">{detail.isLoading ? <LoadingState label="Loading exact source version…" /> : detail.error ? <ErrorState error={detail.error} /> : detail.data ? <><p className="eyebrow">SOURCE PREVIEW</p><h2>{detail.data.artifact.title}</h2><div className="preview-meta"><StatusPill value={detail.data.artifact.lifecycleState} /><span>{detail.data.artifact.sourceProvider}</span><span>{detail.data.versions.length} version(s)</span></div>{detail.data.artifact.canonicalUrl && <a href={detail.data.artifact.canonicalUrl} target="_blank" rel="noreferrer">Open canonical source ↗</a>}<h3>Current content</h3><div className="source-content">{detail.data.versions[0]?.content || 'No current content.'}</div><h3>Relationships</h3>{detail.data.relationships.length ? <ul className="relationship-list">{detail.data.relationships.map(link => <li key={link.id}><b>{link.relationshipType.replaceAll('_', ' ')}</b><span>{link.provenanceType} provenance</span></li>)}</ul> : <p className="muted">No explicit relationships yet.</p>}<h3>Version lineage</h3><ul className="version-list">{detail.data.versions.map(version => <li key={version.id}><code>{version.sourceVersion}</code><span>{new Date(version.validFrom).toLocaleString()}</span><StatusPill value={version.validTo ? 'SUPERSEDED' : 'CURRENT'} /></li>)}</ul></> : <EmptyState title="Select an evidence item" body="Inspect exact content, provenance, relationships, and temporal lineage." />}</aside></section>}</>;
}
